# /// script
# requires-python = ">=3.12"
# ///
"""Generate the launcher icon's vector drawables.

The icon is a stack of squares that rotate as they shrink. Every square shares
one axis, so the figure keeps its rotary symmetry; that axis sits away from the
middle of the canvas, which is what gives the icon its lean. Two inks: the
plates alternate between the ink and the paper the background layer supplies,
and the innermost plate is the accent.

Like the rest of Gyre's artwork this is maths rather than pixels, so the two
drawables are build products. Change a constant here and run

    uv run tools/generate_launcher_icon.py

to write them again. Do not hand-edit the generated files.
"""

from __future__ import annotations

import math
from pathlib import Path

# The adaptive-icon canvas. Launchers show the middle 72 and keep the rest as
# room to shift the layers against each other.
CANVAS = 108.0

# The figure. SPAN is the outermost plate's circumradius as a fraction of the
# canvas: over 1.0 because the plate has to cover the canvas from an axis that
# is not in the middle of it. OFFSET moves that axis, as a fraction of the
# canvas, along HEADING.
SPAN = 1.10
PLATES = 19
TWIST = 104.0
SHRINK = 0.965
OFFSET = 0.20
HEADING = -45.0

INK = "#FF12263F"
ACCENT = "#FFF0508C"
MONOCHROME = "#FFFFFFFF"

RES = Path(__file__).resolve().parent.parent / "app/src/main/res/drawable"


def plate(index: int) -> list[tuple[float, float]]:
    """The four corners of one plate, in canvas units."""
    angle = math.radians(HEADING)
    cx = CANVAS / 2 + OFFSET * CANVAS * math.cos(angle)
    cy = CANVAS / 2 + OFFSET * CANVAS * math.sin(angle)
    u = index / (PLATES - 1)
    radius = SPAN * CANVAS * (1 - u * SHRINK)
    rotation = math.radians(TWIST) * u
    return [
        (cx + radius * math.cos(rotation + math.pi / 4 + corner * math.pi / 2),
         cy + radius * math.sin(rotation + math.pi / 4 + corner * math.pi / 2))
        for corner in range(4)
    ]


def outline(corners: list[tuple[float, float]]) -> str:
    head, *rest = corners
    tail = " ".join(f"L{x:.3f},{y:.3f}" for x, y in rest)
    return f"M{head[0]:.3f},{head[1]:.3f} {tail} Z"


def bands() -> list[str]:
    """The inked rings, each the gap between one plate and the next.

    A ring is two squares in a single path read even-odd, so the paper shows
    through the middle instead of being painted over. That keeps the foreground
    transparent wherever the background layer should read, which is what lets
    the two layers move against each other without the seam showing.
    """
    return [outline(plate(i)) + " " + outline(plate(i + 1)) for i in range(0, PLATES - 2, 2)]


def vector(paths: list[tuple[str, str, bool]]) -> str:
    """A vector drawable from (path data, fill colour, even-odd) triples."""
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        '<!-- Generated by tools/generate_launcher_icon.py. Do not edit. -->',
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        '    android:width="108dp"',
        '    android:height="108dp"',
        '    android:viewportWidth="108"',
        '    android:viewportHeight="108">',
    ]
    for data, colour, even_odd in paths:
        lines.append("    <path")
        lines.append(f'        android:fillColor="{colour}"')
        if even_odd:
            lines.append('        android:fillType="evenOdd"')
        lines.append(f'        android:pathData="{data}" />')
    lines.append("</vector>")
    return "\n".join(lines) + "\n"


def main() -> None:
    rings = bands()
    core = outline(plate(PLATES - 1))

    foreground = [(ring, INK, True) for ring in rings] + [(core, ACCENT, False)]
    monochrome = [(ring, MONOCHROME, True) for ring in rings] + [(core, MONOCHROME, False)]

    (RES / "ic_launcher_foreground.xml").write_text(vector(foreground), encoding="utf-8")
    (RES / "ic_launcher_monochrome.xml").write_text(vector(monochrome), encoding="utf-8")
    print(f"wrote {len(rings)} rings and a core to {RES}")


if __name__ == "__main__":
    main()
